# 명령어는 $ gem install bundler
# 파일명은 Gemfile

source 'https://rubygems.org'
# 브라우저 실행
gem 'launchy'

# 주식정보
gem 'stock_quote'

# 환율관련 정보
gem 'eu_central_bank'

# HTTP 파서
gem 'httparty'

# 크롤링
gem 'nokogiri'

# 날씨 정보받아오기 
gem 'forecast_io'

# 위도경도 받아 오기.
gem 'geocoder'

# mechanize
gem 'mechanize'